name: Update RSS

on:
  schedule:
    - cron: '0 0 * * *'  # every 24 hours
  workflow_dispatch:       # allow manual run

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        run: node index.js

      - name: Upload debug files
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-artifacts
          path: |
            debug.html
            screenshot.png

      - name: Move RSS to docs
        run: |
          mkdir -p docs
          mv index.xml docs/index.xml

      - name: Commit RSS update
        run: |
          git config user.name "MisterJack49"
          git config user.email "misterjack49@users.noreply.github.com"
          git add docs/index.xml
          git diff --cached --quiet || git commit -m "Update RSS feed"
          git push 
